/**
 * Audit event types.
 *
 * Naming: SUBJECT_ACTION or SUBJECT_ACTION_RESULT, uppercase.
 */
export const AuditEventType = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOCKED: 'USER_LOCKED',
  USER_EMAIL_VERIFIED: 'USER_EMAIL_VERIFIED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  MFA_ENROLL_STARTED: 'MFA_ENROLL_STARTED',
  MFA_ENABLED: 'MFA_ENABLED',
  MFA_DISABLED: 'MFA_DISABLED',
  MFA_CHALLENGE_FAILED: 'MFA_CHALLENGE_FAILED',
  MFA_CHALLENGE_SUCCEEDED: 'MFA_CHALLENGE_SUCCEEDED',
  TOKEN_ISSUED: 'TOKEN_ISSUED',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  REFRESH_TOKEN_REUSE_DETECTED: 'REFRESH_TOKEN_REUSE_DETECTED',
  AUTHORIZATION_GRANTED: 'AUTHORIZATION_GRANTED',
  AUTHORIZATION_DENIED: 'AUTHORIZATION_DENIED',
  CLIENT_CREATED: 'CLIENT_CREATED',
  CLIENT_UPDATED: 'CLIENT_UPDATED',
  CLIENT_DISABLED: 'CLIENT_DISABLED',
  CLIENT_SECRET_ROTATED: 'CLIENT_SECRET_ROTATED',
  SUSPICIOUS_LOGIN: 'SUSPICIOUS_LOGIN',
} as const;

export type AuditEventTypeValue = (typeof AuditEventType)[keyof typeof AuditEventType];

export interface AuditEvent {
  event_type: AuditEventTypeValue | string;
  user_id?: string | null;
  client_id?: string | null;
  ip?: string | null;
  user_agent?: string | null;
  request_id?: string | null;
  metadata?: Record<string, unknown>;
}
